### ISSUE TITLE
Tracking issue for ArrayQueue improvments

### ISSUE THREAD

**Issue by alex-dukhno** [Alex-Diez/Rust-Concurrency#3]
- [x] Rename BoundedBlockingQueue to ArrayBlockingQueue
- [x] Move Arc usage inside Queue
- [x] Write benchmarks
- Implement Queue method from [eclectic](https://github.com/apasel422/eclectic) (**sciped**; collection's methods don't take `&mut self`)
- [ ] Add padding for queue elements
